#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Supply
on:
  # TODO: Remove `workflow_call` placeholder + enable for default branch push.
  workflow_call:
  # push:
  #   branches:
  #     - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build:
    name: Build
    uses: ./.github/workflows/.build.yml
  beta:
    name: Beta
    needs:
      - build
    uses: ./.github/workflows/.beta.yml
  publish:
    name: Publish
    needs:
      - beta
    uses: ./.github/workflows/.publish.yml
